<a href="https://www.kaggle.com/code/muhammadasifwazir/python-basic-practice-exercise?scriptVersionId=202589684" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **Import Libraries:**

In [2]:
import numpy as np
import pandas as pd

# **Task 1: Lists, Dictionaries, Tuples** 

## **LISTS:**

In [3]:
my_list_nums =[3,4,7,8,15]
another_list_cube = [num ** 3
                     for num in my_list_nums
                    ]
print("My list of numbers",my_list_nums,'\n',"My new List of cubes numbers", another_list_cube)
# now append the 2nd list into 1st list
my_list_nums.append(another_list_cube)
print(my_list_nums)
#new_extra_list = my_list_nums.extend(another_list_cube)
#print(new_extra_list)

My list of numbers [3, 4, 7, 8, 15] 
 My new List of cubes numbers [27, 64, 343, 512, 3375]
[3, 4, 7, 8, 15, [27, 64, 343, 512, 3375]]


## **Dictionaries**

In [4]:
my_dic = {}
# Adding or intializing all entries of data into dictionary ----> ['key':'value']
my_dic = {'A Person is human not animal':2, 'Cat':4, 'Spider':8, 'Horse':4 }
# Show the corresponding animals legs
for Animal, legs in my_dic.items():
    print(f"{Animal} has : {legs}")
# Now sum of total legs
sum_of_all_legs = sum(my_dic.values())
print(f"total legs : {sum_of_all_legs}")

A Person is human not animal has : 2
Cat has : 4
Spider has : 8
Horse has : 4
total legs : 18


## **TUPLES:**

In [5]:
D = (1,15,4,[5,10])
# change the value in the list from 5 to 3
# Tuble is mutable so we can not change it but we can change the list inside the tuple
# tuble[index in taple][index in list] and assign a value that is 3
D[3][0] = 3
print(f" Our New Tuple: {D}")
# Delete the Tuple
new_tuple = (804,804)

del new_tuple

# initialize the tuple
E = ('a','p','p','l','e')
print(f"New Tuple: {E}")
# Now check the number of occurrences of 'p' in tuple E 
E.count('p')
print(f"count of P in Tuple E : {E.count('p')}")
# Find the index of 'l' in tuple E
E.index('l')
print(f"index number of l in Tuble E : {E.index('l')}")

 Our New Tuple: (1, 15, 4, [3, 10])
New Tuple: ('a', 'p', 'p', 'l', 'e')
count of P in Tuple E : 2
index number of l in Tuble E : 3


# **Task 2: Functions and For Loops**

## **1. Calculate the velocity**

In [6]:
def Compute(distance, time):
    if time == 0:
        return "Time should not be zero"
    return distance / time

# Compute Velocity function
velocity = Compute(100, 10)
print(f"Velocity: {velocity} m/s")

Velocity: 10.0 m/s


## **2. Calculate the sum of all the even numbers till 20 of a list**

In [7]:
# List of even numbers from 2 to 20
even = [i for i in range(2, 21, 2)]
def Sum(lst):
    total = 0
    for num in lst:
        total += num
    return total
# Sum of Even Numbers
even_sum = Sum(even)
print(f"Sum of even numbers till 20: {even_sum}")

Sum of even numbers till 20: 110


## **3. Find the intersection of the two lists**

In [8]:
def Intersection(list1, list2):
    return [x for x in list1 if x in list2]

list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
intersection_result = Intersection(list1, list2)
print(f"Intersection of list1 and list2: {intersection_result}")

Intersection of list1 and list2: [4, 5]


## **4. Combine two dictionaries**

In [9]:
def CombineDicts(dict1, dict2):
    combined = {}
    for key in dict1:
        combined[key] = dict1[key] + dict2.get(key, 0)
    for key in dict2:
        if key not in combined:
            combined[key] = dict2[key]
    return combined

# a and b dictionaries
a = {'one': 12, 'two': 10, 'three': 22}
b = {'four': 14, 'one': 10, 'three': 2}
combined_dict = CombineDicts(a, b)
print(f"Combined dictionary: {combined_dict}")

Combined dictionary: {'one': 22, 'two': 10, 'three': 24, 'four': 14}


## **5. Write a function to return a dictionary with only odd values**

In [10]:
def FilterOddValues(d):
    return {k: v for k, v in d.items() if v % 2 != 0}

# initialize the dictionary as my_dict
my_dict = {'a': 17, 'b': 2, 'c': 25, 'd': 0, 'e': 29, 'f': 32, 'g': 13}
odd_values_dict = FilterOddValues(my_dict)
print(f"only odd values dictionary: {odd_values_dict}")

only odd values dictionary: {'a': 17, 'c': 25, 'e': 29, 'g': 13}


## **6. Generate two lists programmatically, sum them element by element**

In [11]:
# List of the first 12 odd numbers
odd_numbers = [i for i in range(1, 25, 2)]

# List of the first 12 multiples of 3
multiples_of_3 = [i * 3 for i in range(1, 13)]

# Add corresponding elements from the two lists
added_lists = [odd + multiple for odd, multiple in zip(odd_numbers, multiples_of_3)]
print(f"Element-wise addition of odd_numbers and multiples_of_3: {added_lists}")


Element-wise addition of odd_numbers and multiples_of_3: [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]


# **Task 3: Numpy**

In [12]:
# The Given matrix M and vector z
M = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])

z = np.array([1, 0, 1])

# 1. Matrix M as a numpy array (Already provided)
print("Matrix M:\n", M)

# 2. Slicing the first 2 rows and 2 columns
b = M[:2, :2]
print("Subarray b (2x2):\n", b)

# 3. Create an empty matrix y with the same shape as M
y = np.empty_like(M)

# 4. Add vector z to each column of M
for i in range(M.shape[1]):
    y[:, i] = M[:, i] + z
print("Matrix y after adding z:\n", y)

# Given matrices A, B, and vector v
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])

# 1. Add matrices A and B
C = A + B
print("A + B:\n", C)

# 2. Element-wise multiplication of A and B
D = A * B
print("A * B (element-wise):\n", D)

# 3. Element-wise square root of A
E = np.sqrt(A)
print("Element-wise square root of A:\n", E)

# 4. Dot product of A and v
dot_product = np.dot(A, v)
print("Dot product of A and v:\n", dot_product)

# 5. Sum of each column of A
column_sum = np.sum(A, axis=0)
print("Sum of each column of A:\n", column_sum)

# 6. Transpose of B
B_transpose = np.transpose(B)
print("Transpose of B:\n", B_transpose)

# Compute weights for machine learning model
X = np.array([
    [1, 1, 4],
    [1, 2, 5],
    [1, 3, 8],
    [1, 4, 2]
])

Y = np.array([1, 6, 8, 12])

X_transpose = X.T
B_matrix = np.dot(np.linalg.inv(np.dot(X_transpose, X)), np.dot(X_transpose, Y))
print("Computed weights (B matrix):\n", B_matrix)


Matrix M:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Subarray b (2x2):
 [[10 11]
 [14 15]]
Matrix y after adding z:
 [[11 12 13 14]
 [14 15 16 17]
 [19 20 21 22]]
A + B:
 [[ 6  8]
 [10 12]]
A * B (element-wise):
 [[ 5 12]
 [21 32]]
Element-wise square root of A:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Dot product of A and v:
 [29 67]
Sum of each column of A:
 [4 6]
Transpose of B:
 [[5 7]
 [6 8]]
Computed weights (B matrix):
 [-1.69945355  3.48360656 -0.05464481]


# **Task 4: Pandas DataFrame**

## **Create a DataFrame pd that contains 5 rows and 4 columns**

In [13]:
# Creating a DataFrame with 5 rows and 4 columns
data = {
    'F1': [1, 2, 3, 4, 5],
    'F2': [6, 7, 9, 8, 2],
    'F3': [81, 90, 94, 92, 88],
    'F4': [7, 700, 900, 60, 4]
}
pd_df = pd.DataFrame(data)

# Display the created DataFrame
print("Initial DataFrame:\n", pd_df)

Initial DataFrame:
    F1  F2  F3   F4
0   1   6  81    7
1   2   7  90  700
2   3   9  94  900
3   4   8  92   60
4   5   2  88    4


## **2. Print only the first two rows of the DataFrame**

In [14]:
# Using the .head() function to display the first two rows
print("\nFirst two rows of the DataFrame:\n", pd_df.head(2))


First two rows of the DataFrame:
    F1  F2  F3   F4
0   1   6  81    7
1   2   7  90  700


## **3. Print the second column**

In [15]:
# Accessing the second column 'F2'
print("\nSecond column (F2):\n", pd_df['F2'])


Second column (F2):
 0    6
1    7
2    9
3    8
4    2
Name: F2, dtype: int64


## **4. Change the name of the third column to ‘Feature3’**

In [16]:
# Renaming the third column 'F3' to 'Feature3'
pd_df.rename(columns={'F3': 'Feature3'}, inplace=True)

## **5. Add a new column to the DataFrame and name it ‘Sum’**

In [17]:
# Adding a new column 'Sum' that contains the sum of each row
pd_df['Sum'] = pd_df.sum(axis=1)

# Displaying the DataFrame after adding the new column 'Sum'
print("\nDataFrame after adding 'Sum' column:\n", pd_df)



DataFrame after adding 'Sum' column:
    F1  F2  Feature3   F4   Sum
0   1   6        81    7    95
1   2   7        90  700   799
2   3   9        94  900  1006
3   4   8        92   60   164
4   5   2        88    4    99


> # **END**